name: CI pipeline

on:
  push:
    branches: ["release/*", "main"]
  workflow_dispatch:


jobs:
  git-codes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show git info
        run: |
          git status
          git log --oneline -5
          git branch -vv